module for max-movies-in-years
Real-Software-Dev-Squad/Max-Movies-In-Years pull request #1
Opened 2020-03-14 16:54 UTC by Kratika0907

2020-03-15 17:09 UTC, ankushdharkar commented
@Kratika0907 Updated the API format details in https://github.com/Real-Software-Dev-Squad/Max-Movies-In-Years/blob/master/README.md, please check and submit again in the same PR

2020-03-16 02:40 UTC, Kratika0907 commented
max-movies-in-years solution

2020-03-16 08:52 UTC, ankushdharkar requested changes
Please use `const` for values that will not be changing their references

2020-03-16 08:52 UTC, ankushdharkar commented on Max-Movies-In-Years.js
> +let res = [
This should be `const`

2020-03-16 08:52 UTC, ankushdharkar commented on Max-Movies-In-Years.js
> +  let licenseArray = res.reduce((acc, element) => {
This should be `const`

2020-03-16 08:52 UTC, ankushdharkar commented on Max-Movies-In-Years.js
> +  let yearMap = new Map();
This should be `const`

2020-03-17 20:45 UTC, ankushdharkar commented on Max-Movies-In-Years.js
> +const res = [
Let's remove this file. Always try to get rid of stray code that's not serving purpose

2020-03-17 20:47 UTC, ankushdharkar commented on Max-Movies-In-Years-2.js
> +function displayMap(map) {
Indentations are all off. Please format properly

2020-03-17 20:50 UTC, ankushdharkar commented on README.md
> +Time Complexity = O(nlogn) where n is the number of element in years array
Please add some more details on why

2020-03-17 20:50 UTC, ankushdharkar commented on Max-Movies-In-Years-2.js
> +       const minYear =years[0];
What happens if `years` has a length of 0?

2020-03-17 20:51 UTC, ankushdharkar commented on Max-Movies-In-Years-2.js
> +       }
Maybe move to a separate function for readability?

2020-03-17 20:52 UTC, ankushdharkar commented on Max-Movies-In-Years-2.js
> +       }
You can check if the map already has it and then add, or set as 1

Less code = Fewer mistakes + More confidence

2020-03-17 20:53 UTC, ankushdharkar commented on Max-Movies-In-Years-2.js
> +            },[]).sort((a,b)=>a-b)
Do you *need* to sort?

2020-03-17 20:56 UTC, ankushdharkar commented on Max-Movies-In-Years-2.js
> +            },[]).sort((a,b)=>a-b)
Is the sort comparator correct? 

```js
year = [ 2001, 2002 ]
```

What is `(a - b)`?

2020-03-17 20:59 UTC, ankushdharkar commented on README.md
> +Space Complexity = O(n) => map and array
Is this correct? Please re-evaluate

2020-03-19 17:58 UTC, ankushdharkar commented on .prettierrc
> +    "singleQuote": true
Don't push these unnecessary files please

2020-03-19 17:59 UTC, ankushdharkar commented on Max-Movies-In-Years-2.js
> +
Any reason why there is `-2` in the name? and a file with `-3`

Remove dead code please

2020-03-22 05:28 UTC, Kratika0907 commented
Created a new PR while adhering comments and also added the discussed solution for same.
PR : [https://github.com/Real-Software-Dev-Squad/Max-Movies-In-Years/pull/15](url)

2020-03-22 05:28 UTC, closed without merging