Add: Solution for Max Movies in Year
Real-Software-Dev-Squad/Max-Movies-In-Years pull request #2
Opened 2020-03-15 15:18 UTC by codecrook

My solution to the task in "Real Software Dev Squad" first-task.
, Max Movies in Year

2020-03-15 17:09 UTC, ankushdharkar commented
@codecrook Solution is incorrect. Please check your usecases again

2020-03-15 19:03 UTC, codecrook commented
Hi @ankushdharkar ! 
Updated the solution. Please review again.

2020-03-15 19:13 UTC, ankushdharkar requested changes

2020-03-15 19:13 UTC, ankushdharkar commented on maxMoviesInYear.js
> +    if (moviesList.length === 0) return [];
Do we need this line?

The more logic you don't  branch off, the better you prevent the cognitive overload

2020-03-15 19:17 UTC, ankushdharkar commented
@codecrook Your logic works. But readability of your code is low

Let's break it into easy to understand functions. The smaller the parts you have to reason about, the more confidence in the code working and easier to maintain over long-term

```js
function maxMoviesInYears(moviesList) {
    const years = getYearsFromList(moviesList);
    const maxMovieYears = getMaxMovieYearsFromYears(years);
    return [...maxMovieYears];
}
```

2020-03-15 19:20 UTC, ankushdharkar commented
@codecrook What is the time complexity and space complexity of your solution?

2020-03-15 19:51 UTC, codecrook commented
Hi @ankushdharkar ,
Made the code changes as per review comments.
I understand time-complexity is a big problem here. Will improve on the course of my learning here.🙂

2020-03-17 18:19 UTC, codecrook commented
Hi @ankushdharkar !
Added the time and space complexity calculations.
Please review.

2020-03-17 20:44 UTC, ankushdharkar requested changes

2020-03-17 20:44 UTC, ankushdharkar commented on README.md
> +Calling both the functions above one time each, it will be having `O(N^2) + O(N^2) = O(N^2)`
O(N<sup>2</sup>) seems bad. Can you improve please?

2021-01-14 18:03 UTC, closed without merging